# Generated by Django 4.2.3 on 2023-08-15 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Orchids', 'Orchids'), ('Peony', 'Peony'), ('Roses', 'Roses'), ('Tulips', 'Tulips'), ('Lilies', 'Lilies'), ('Magnolia', 'Magnolia'), ('Cyclamen', 'Cyclamen'), ('Hyacinth', 'Hyacinth'), ('Bamboo', 'Bamboo'), ('Succulent', 'Succulent')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('color', models.CharField(choices=[('pink', 'pink'), ('violet', 'violet'), ('white', 'white'), ('blue', 'blue'), ('red', 'red'), ('yellow', 'yellow'), ('mix', 'mix')], max_length=50)),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Graduation', 'Graduation'), ('Weeding', 'Weeding'), ('Motherday', 'Motherday'), ('Anniversary', 'Anniversary')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=3)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='eShopFlowery.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eShopFlowery.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eShopFlowery.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eShopFlowery.favorite')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eShopFlowery.product')),
            ],
        ),
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eShopFlowery.product'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eShopFlowery.userprofile'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=3)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eShopFlowery.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eShopFlowery.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eShopFlowery.userprofile'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eShopFlowery.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'product')},
        ),
    ]
