# Generated by Django 4.2.3 on 2023-08-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eShopFlowery', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='product',
        ),
    ]
