# Generated by Django 4.2.3 on 2023-08-15 22:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eShopFlowery', '0002_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='payment_method',
            field=models.CharField(choices=[('On Delivery', 'On Delivery'), ('Card', 'Card')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eShopFlowery.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Created', 'Created'), ('InDelivery', 'InDelivery'), ('Finished', 'Finished')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='card_holder_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='card_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='card_type',
            field=models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='exp_mm',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='exp_yy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='eShopFlowery.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='security_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='eShopFlowery.cart'),
        ),
    ]
